/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StarredLazyImport = createFileRoute('/starred')()
const DetailsLazyImport = createFileRoute('/details')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const StarredLazyRoute = StarredLazyImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/starred.lazy').then((d) => d.Route))

const DetailsLazyRoute = DetailsLazyImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/details.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsLazyImport
      parentRoute: typeof rootRoute
    }
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/details': typeof DetailsLazyRoute
  '/starred': typeof StarredLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/details': typeof DetailsLazyRoute
  '/starred': typeof StarredLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/details': typeof DetailsLazyRoute
  '/starred': typeof StarredLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/details' | '/starred'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/details' | '/starred'
  id: '__root__' | '/' | '/details' | '/starred'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DetailsLazyRoute: typeof DetailsLazyRoute
  StarredLazyRoute: typeof StarredLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DetailsLazyRoute: DetailsLazyRoute,
  StarredLazyRoute: StarredLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/details",
        "/starred"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/details": {
      "filePath": "details.lazy.tsx"
    },
    "/starred": {
      "filePath": "starred.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
