/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

// Create Virtual Routes

const StarredLazyImport = createFileRoute("/starred")();

// Create/Update Routes

const StarredLazyRoute = StarredLazyImport.update({
  id: "/starred",
  path: "/starred",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/starred.lazy").then((d) => d.Route));

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/starred": {
      id: "/starred";
      path: "/starred";
      fullPath: "/starred";
      preLoaderRoute: typeof StarredLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/starred": typeof StarredLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/starred": typeof StarredLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/starred": typeof StarredLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/starred";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/starred";
  id: "__root__" | "/" | "/starred";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  StarredLazyRoute: typeof StarredLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StarredLazyRoute: StarredLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/starred"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/starred": {
      "filePath": "starred.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
